### Get all commits
GET http://localhost:8080/api/commits

### Get commit by sha
GET http://localhost:8080/api/commits/02af2acb-fa0b-4074-99d8-7e104ed2096d

### Update commit
PUT http://localhost:8080/api/commits/02af2acb-fa0b-4074-99d8-7e104ed2096d
Content-Type: application/json

{
  "sha": "02af2acb-fa0b-4074-99d8-7e104ed2096d",
  "name": "Add Factory GoF pattern implementation",
  "description": "Factory pattern is one of GoF base pattern and we need this implementation",
  "upload": true
}

### Create commit
POST http://localhost:8080/api/commits
Content-Type: application/json

{
  "name": "Add Proxy pattern implementation",
  "repositoryName": "design-patterns",
  "authorName": "iluvatar"
}